# output "eks_cluster_endpoint" {
#   value = aws_eks_cluster.aws_eks.endpoint
# }

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

# output "eks_cluster_certificate_authority" {
#   value = aws_eks_cluster.aws_eks.certificate_authority 
# }
